server:
  port: 7000
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比
  application:
    name: api-gateway
  cloud:
    gateway:
      routes: # 路由数组[]
        - id: product_route
#          uri: http://localhost:8081
          uri: lb://service-product # lb指的是负载均衡,后面跟的是具体微服务标识
          predicates:
            - Path=/product-serv/**
            - Before=2030-11-28T00:00:00.000+08:00
#            - Age=18,60 # 仅仅让age18-60之间的人访问
          filters:
            - StripPrefix=1
        - id: order_route
          uri: lb://service-order # lb指的是负载均衡,后面跟的是具体微服务标识
          predicates:
            - Path=/order-serv/**
            - Before=2030-11-28T00:00:00.000+08:00
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true # 让gateway从nacos种获取服务信息
    nacos:
      server-addr: localhost:8848 # 将gateway注册到nacos