server:
  port: 5113
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:59171/zipkin?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root
zipkin:
  storage:
    type: mysql
management:
  metrics:
    web:
      server:
        auto-time-requests: false