server:
  port: 8091
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://gz-cdb-11om9s8x.sql.tencentcdb.com:59171/shop?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: sC_6^NS+zZ8a
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#rocketmq
#rocketmq:
#  name-server: 192.168.109.131:9876